M48
; DRILL file {KiCad 7.0.6} date Tue Aug  8 22:31:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-08T22:31:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X3.9425Y-2.2224
X4.2679Y-2.2224
T2
X3.8553Y-2.1516
X4.3553Y-2.1516
T0
M30
